# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('matricula', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_com_hora', models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='www.Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('horario', models.CharField(max_length=50)),
                ('dataInicio', models.DateField(verbose_name='Data de Inicio')),
                ('dataFinal', models.DateField(verbose_name='Data final')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='www.Turma'),
        ),
    ]
