# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0003_aluno_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
