# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0004_auto_20170202_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='email',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
